server:
  port: 18080

spring:
  cloud:
    gateway:
      routes:
        # 管理模块
        - id: bite-mstemplate
          uri: lb://bite-mstemplate
          predicates:
            - Path=/mstemplate/**
          filters:
            - StripPrefix=1
